apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBtG5vjxWmdWJ7EBkKUG4bPtUeaquAeKD46YegbSUHZGrZ2LFL1r3d/ZS5vC60mR3sFnO41aVpvZxe91CxZDalJGw+hMJ9taJxv1i/ySjIBIg75K3JkhM1+humYuEidjYn23/Mj+zDDKMGwP6skObMzVxJudIJP6DXrx4dBnY8PK0culQyMPRB0MTBv9oWo5/L93vNo+ILF926WStlUzQhf+0H2adf54+eH5hk/JMVKRv6MF69Gc69pqp7NbXJSO79VRi6H54MMBiOu9qEYS/jToUNr8jAYXpkUHYNk4kzhE2KplcbOqgQS5/BauFDWHVeYmtONprGduExc9B2BbF/ORBjDuXJfsrzYEiP7L2KCkaf8Msp4q1i0R0vJYEVLAhfcHxct7UEf05Kzv5kMAAekHiEBSW7HjTH5pjQwnScqNC8DaHmtu5jhz2vEYvz7qQNVATWSwssflrG3un6hnJDzIFBuU94aup9ygAVatuGhQZ+NFOxM70mbGF41ceGctwFHV1AffVQkyMCLCfC8Ee4OHxh8y1spw8jTaMoWNeSEKs+Vrs+8rhuQSq2FWB7ePZCl8CLXhFfRkSnE0RpwlsMo3MqKatyTGx1g4MeJm3xNU8g8UptLzYM4wSCgroXcgr4hFVgspNbXcLp17EMTTix7fK3mThfMpce0A2FwY7Q17iuC9oE26xP3VVxzFHtzaQo=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

